package com.trevasq.qguard.service;
import com.trevasq.qguard.api.ApiDtos.*; import com.trevasq.qguard.config.AppProperties; import com.trevasq.qguard.domain.*; import jakarta.transaction.Transactional; import java.time.*; import java.util.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service;
@Service public class BookingService { private final BookingRepository repo; private final SchedulingService schedule; private final TokenService tokens; private final NotificationService notify; private final AppProperties p;
 public BookingService(BookingRepository r,SchedulingService s,TokenService t,NotificationService n,AppProperties p){repo=r;schedule=s;tokens=t;notify=n;this.p=p;}
 @Transactional public CreatedBookingResponse create(CreateBookingRequest r){schedule.assertBookable(r.startsAt());String token=tokens.create();Booking b=new Booking(UUID.randomUUID(),r.name().trim(),r.email().trim().toLowerCase(),r.company().trim(),r.jobTitle().trim(),blankToNull(r.phone()),r.startsAt(),r.startsAt().plusSeconds(1800),tokens.hash(token));try{repo.saveAndFlush(b);}catch(DataIntegrityViolationException e){throw new SchedulingService.SlotTakenException();}String url=managementUrl(token);notify.confirmation(b,url);return new CreatedBookingResponse(dto(b,zone(r.timezone())),url);}
 @Transactional public BookingResponse reschedule(String token,RescheduleRequest r){Booking b=managed(token);schedule.assertBookable(r.startsAt());try{b.reschedule(r.startsAt());repo.saveAndFlush(b);}catch(DataIntegrityViolationException e){throw new SchedulingService.SlotTakenException();}notify.confirmation(b,managementUrl(token));return dto(b,zone(r.timezone()));}
 @Transactional public void cancel(String token){Booking b=managed(token);if(b.getStatus()==BookingStatus.CANCELLED) return;b.cancel();repo.save(b);}
 @Transactional public BookingResponse get(String token){return dto(managed(token),p.businessZone());}
 private Booking managed(String token){return repo.findByManagementTokenHash(tokens.hash(token)).orElseThrow(UnknownManagementTokenException::new);} private String managementUrl(String token){return p.publicBaseUrl()+"/manage/"+token;} private ZoneId zone(String zone){try{return ZoneId.of(zone);}catch(Exception e){throw new IllegalArgumentException("Invalid IANA timezone");}} private BookingResponse dto(Booking b,ZoneId z){return new BookingResponse(b.getId(),b.getName(),b.getEmail(),b.getCompany(),b.getJobTitle(),b.getPhone(),b.getStartsAt(),b.getEndsAt(),b.getStatus().name(),z.getId());} private String blankToNull(String x){return x==null||x.isBlank()?null:x.trim();} public static class UnknownManagementTokenException extends RuntimeException{} }
